### ISSUE TITLE
how to train  based other  dataset? 

### ISSUE THREAD

**Issue by wqqLuke** [HYPJUDY/Decouple-SSAD#10]
i have some problems about how to use your code to my dataset?
example gen window_info、gt_label、annotation.csv eg..

**Comment by HYPJUDY** [comment]
Please see [Preprocess Data by Yourself](https://github.com/HYPJUDY/Decouple-SSAD/blob/master/data/README.md#preprocess-data-by-yourself).

**Comment by xianguo-dev** [comment]
Hi！Have you  succeed in training ur own dataset yet？
