### ISSUE TITLE
Matching the default anchors with gt 

### ISSUE THREAD

**Issue by rahman-mdatiqur** [HYPJUDY/Decouple-SSAD#11]
Hello @HYPJUDY ,

when you match the default anchors with gt bboxes, you are checking if the overlap is greater than -0.5 or not as in this [line](https://github.com/HYPJUDY/Decouple-SSAD/blob/master/operations.py#L84). Since, the overlaps can never be negative, what is the implication of the below line ?
`mask = tf.logical_and(mask, b_match_scores > -0.5)`

Thanks.

**Comment by rahman-mdatiqur** [comment]
Hello @HYPJUDY ,
can you please respond?

**Comment by HYPJUDY** [comment]
I am also confused. It's adopted from the original SSAD code. I only add a comment line when using this part.
https://github.com/HYPJUDY/Decouple-SSAD/blob/9a78cea6be27f9cc7cd512e027f00526be5ecad8/operations.py#L80
I've consulted the original coder, he said it's refered from a tensorflow code of SSD and maybe the `-0.5` is not necessary. Only `mask = tf.logical_and(mask, b_match_scores > 0)` is enough. Please provide feedback if it doesn't work.
Thanks!

**Comment by rahman-mdatiqur** [comment]
Thanks much for your detailed feedback. I highly appreciate your quick response. I will let you know how it performs without this line.

**Comment by rahman-mdatiqur** [comment]
Hello @HYPJUDY ,

I did not find any difference in performance with that line commented out.

Thanks for all your help.

**Comment by HYPJUDY** [comment]
Thanks for testing this!
