### ISSUE TITLE
Need more details to preprocess data on my own data

### ISSUE THREAD

**Issue by jalaxy33** [HYPJUDY/Decouple-SSAD#13]
Hello, @HYPJUDY .

I want to use the D-SSAD on my own dataset. I follow the instruction you gave in the [Preprocess Data by Yourself](https://github.com/HYPJUDY/Decouple-SSAD/tree/master/data#preprocess-data-by-yourself), and get the frames and flow images extracted from my own dataset by the [TSN](https://github.com/yjxiong/temporal-segment-networks#extract-frames-and-optical-flow-images).

Now I am stuck in the step 3. I have put the [data/gen_thumos14_anno.py](https://github.com/HYPJUDY/Decouple-SSAD/blob/master/data/gen_thumos14_anno.py) in the root directory of the [SSN](https://github.com/yjxiong/action-detection) and made some directory mismatch modification. I don't know what to do next, mainly because I don't know how to create my own 'proposal_list.txt'. I found that the SSN code is all about thumos14 and activitynet, and I feel struggled to adjust the code to my own dataset.

I am confused now and asking for help. So could you please show me more details about the SSN data-preprocessing step?

**Comment by HYPJUDY** [comment]
Hi @jadada , you can refer to the process of generating of proposal list in SSN. For example, you may need to generate a normalized proposal list firstly, as mentioned in the [readme](https://github.com/yjxiong/action-detection#prepare-the-proposal-lists). 
To generate the normalized proposal list, 
(1) you can refer to the [example of thumos14 dataset](https://raw.githubusercontent.com/yjxiong/action-detection/master/data/thumos14_tag_val_normalized_proposal_list.txt) and read [this code](https://github.com/yjxiong/action-detection/blob/master/ops/io.py) to understand the meaning of each value and the structure of proposal list.
(2) you can compare the [example of thumos14 dataset](https://raw.githubusercontent.com/yjxiong/action-detection/master/data/thumos14_tag_val_normalized_proposal_list.txt) and the [thumos14 annotations](https://github.com/yjxiong/action-detection/tree/master/data/thumos_14) of thumos14 to understand their forms.
Then you may imitate the way and transfer from thumos14 to your own dataset.
For more details, I suggest you to ask help from SSN repo. You may refer to [their issues panel](https://github.com/yjxiong/action-detection/issues?utf8=%E2%9C%93&q=proposal+list) too.
Good luck!

**Comment by Flyzanetothesky** [comment]
Hi @jadada, @HYPJUDY , there is seem no need to get  'proposal_list.txt'.  The third step in [https://github.com/HYPJUDY/Decouple-SSAD/tree/master/data#preprocess-data-by-yourself](url) only generate validation and test set **ground truth annotations** based on [https://github.com/yjxiong/action-detection](url). So for your own dataset, if you train Decouple-SSAD, you only need generate your ground truth label manual.

**Comment by Flyzanetothesky** [comment]
Hi @jadada @HYPJUDY ,  Is your own dataset refers to the “thumos-14” ?  If not, you can skip the third step of [Preprocess Data by Yourself](https://github.com/HYPJUDY/Decouple-SSAD/blob/master/data/README.md) and label your data manual. thus, you could get ground truth annotations.

**Comment by xianguo-dev** [comment]
@jadada Have you create your own 'proposal_list.txt' yet?I got the same problem and still can not make it.

**Comment by xianguo-dev** [comment]
@HYPJUDY Hi! Thanks for your kind reply here.

  But I am still confused about this" normalized_proposal_list" .Does SSN provide code to generate it? Because I found gen_proposal_list.py uses the authors' own " normalized_proposal_list" files. I could not find any code to generate  proposal list and am struggling to imitate its content.

  However, the data is too large and it's impossible to type my own proposal list one by one manually .So I'd like to know i that is there any code provided to generate the " normalized_proposal_list" or we really have to generate it by ourselves?

  Looking forward to your generous help!

**Comment by HYPJUDY** [comment]
Hi, I do not have that code. I tried to search the answers in their repos but failed. It seems that some other people (e.g., https://github.com/yjxiong/action-detection/issues/100, https://github.com/open-mmlab/mmaction/issues/102) also have the same requirement to generate the normalized proposal lists but didn't work out. Maybe the best way is to write the code by yourself or email the original author.
FYI, [A Description of the Proposal Files](https://github.com/yjxiong/action-detection/wiki/A-Description-of-the-Proposal-Files) might helps.

**Comment by xianguo-dev** [comment]
Thanks anyway,I've watched through all the issues in SSN and mmaction.But I still can't find any useful information except **Description of the Proposal Files**,which helps a bit.

Thanks again for you've made me realize throughly that I should find other ways.

**Comment by HYPJUDY** [comment]
You are welcome! Wish you find a solution!

**Comment by xianguo-dev** [comment]
@HYPJUDY Hi!I have worked out the specific meaning of most of the data in“ normalized_proposal_list ”but I still could not understand the origin of **num_prop**.I could not understand the data structure as the following part in“ normalized_proposal_list ” :

video_test_0000021
1
1
0
**29
0 0.0000 0.0000 0.3955 0.4200
0 0.0000 0.0000 0.1335 0.1702
0 0.0000 0.0000 0.7125 0.7492
0 0.0000 0.0000 0.3109 0.3405
0 0.0000 0.0000 0.3833 0.4322
0 0.0000 0.0000 0.9327 0.9633
0 0.0000 0.0000 0.3048 0.3466
0 0.0000 0.0000 0.3772 0.4383
0 0.0000 0.0000 0.7003 0.7615
0 0.0000 0.0000 0.1213 0.1825
0 0.0000 0.0000 0.3649 0.4506
0 0.0000 0.0000 0.6942 0.7737
0 0.0000 0.0000 0.2926 0.3588
0 0.0000 0.0000 0.1030 0.2069
0 0.0000 0.0000 0.3109 0.4322
0 0.0000 0.0000 0.2926 0.4506
0 0.0000 0.0000 0.2742 0.4628
0 0.0000 0.0000 0.6942 0.9633
0 0.0000 0.0000 0.1030 0.4628
0 0.0000 0.0000 0.6758 1.0000
0 0.0000 0.0000 0.3833 0.7492
0 0.0000 0.0000 0.3109 0.7492
0 0.0000 0.0000 0.3649 0.9633
0 0.0000 0.0000 0.1335 0.7615
0 0.0000 0.0000 0.2926 0.9633
0 0.0000 0.0000 0.1335 0.3466
0 0.0000 0.0000 0.1213 0.3588
0 0.0000 0.0000 0.1213 0.9633
0 0.0000 0.0000 0.1335 0.4383**

It seems that it does not have any regulation and the description you advised me to look at also does not introduce these numbers.

And I suppose that these numbers are random and are used in the parts of training and testing(randomize samples and locate frames) .

Would you please give me some advice?Sorry to interrupt you.

**Comment by HYPJUDY** [comment]
Hi @xianguo-dev , is this ([A Description of the Proposal Files](https://github.com/yjxiong/action-detection/wiki/A-Description-of-the-Proposal-Files) ) what you are looking for?

**Comment by xianguo-dev** [comment]
Thanks for your reply!Right.And I don't understand the following part:

11
86 0.9045 0.9625 0.1277 1.0000
86 0.8943 0.8943 0.0000 1.0000
86 0.8349 0.9595 0.1915 1.0000
86 0.3650 0.9121 0.6277 1.0000
86 0.3302 0.9037 0.6596 1.0000
86 0.2954 0.8936 0.6915 1.0000
86 0.2606 0.8810 0.7234 1.0000
86 0.2886 1.0000 0.1277 0.3856
86 0.2345 1.0000 0.1436 0.3537
86 0.1804 1.0000 0.1596 0.3218
86 0.1263 1.0000 0.1915 0.3059

The problem is that why this video has 11 proposals and how to generate this part?I have watched the corresponding video and find nothing special during these proposals.

**Comment by HYPJUDY** [comment]
I think they are the ground truth annotations, labeld by annotators.
