### ISSUE TITLE
About the overlap loss

### ISSUE THREAD

**Issue by dagongji10** [HYPJUDY/Decouple-SSAD#15]
In your paper, I see overlap loss is 
![image](https://user-images.githubusercontent.com/15357846/68373817-99704400-017e-11ea-8e21-e119da541532.png), 
it conbine main_branch and proposal_branch. But in the code it is 
![image](https://user-images.githubusercontent.com/15357846/68373925-ccb2d300-017e-11ea-9380-5cacdabe87db.png), 
it only use proposal_branch.
Why ? Is there any tips ?

**Comment by HYPJUDY** [comment]
Though I want to unified the `conf_loss` as the same parameter setting as other losses, I found the performance would be better by not involving `main_conf_loss` into `conf_loss` in my experiments. I cannot explain this phenomenon in theory. Maybe you can try in your case.
Thanks.

**Comment by rahman-mdatiqur** [comment]
Hi @HYPJUDY ,

also I noticed that you have used Smooth-L1 loss for the Overlap-loss, but in the paper you mentioned that you used Mean-Squared-Error loss for Overlap-loss. Can you please explain why the difference exists?

**Comment by HYPJUDY** [comment]
Hi @atique81 , sorry for the inconsistency. The code of smooth-L1 loss is directly adopted from SSAD and we didn't clarify this detail in paper.
"Smooth L1-loss can be interpreted as a combination of L1-loss and L2-loss"[ref](https://stats.stackexchange.com/questions/351874/how-to-interpret-smooth-l1-loss). Smooth-L1 loss may perform better than MSE (I didn't do ablation study), but their motivation is similar: to minimize the gap between predicted values and ground truth values. So it should be fine to use both.

**Comment by rahman-mdatiqur** [comment]
Hello @HYPJUDY ,
Thanks for the clarification.
