### ISSUE TITLE
what is the meaning of the "classList" in gen_thumos14_anno.py?

### ISSUE THREAD

**Issue by jalaxy33** [HYPJUDY/Decouple-SSAD#17]
what does each number in the list stand for in the [gen_thumos14_anno.py](https://github.com/HYPJUDY/Decouple-SSAD/blob/master/data/gen_thumos14_anno.py#L21). Is it the same as the "type_idx" params in this [csv file](https://github.com/HYPJUDY/Decouple-SSAD/blob/master/data/thumos14/val/thumos14_val_annotation.csv)?

**Comment by HYPJUDY** [comment]
Yes, these numbers (0, 7, 9, 12, 21...) are the ``type_idx`` where you can find in the [csv file](https://github.com/HYPJUDY/Decouple-SSAD/blob/master/data/thumos14/val/thumos14_val_annotation.csv). They are official definition and should be used for the official evaluation code.
https://github.com/HYPJUDY/Decouple-SSAD/blob/e3b65392cc4be7dd3887bd38996792ce6dc698f0/data/gen_thumos14_anno.py#L21-L25
https://github.com/HYPJUDY/Decouple-SSAD/blob/e3b65392cc4be7dd3887bd38996792ce6dc698f0/config.py#L31-L32

**Comment by jalaxy33** [comment]
Thanks for your quick reply. Now what I truly want to know is how to decide the number tagged to each label? For example, I want to know why 7 is tagged to 'BaseballPitch' and 9 is tagged to 'BasketballDunk'. Is there any rule on this, or I could arbitrarily tag different number to each label?

**Comment by HYPJUDY** [comment]
This is the official definition.
There are 101 classes for UCF101 dataset indexed in alphabetical order: [List of action classes and their numerical index](http://crcv.ucf.edu/THUMOS14/Class%20Index.txt)
THUMOS14 uses a subset of [20 classes](https://github.com/HYPJUDY/Decouple-SSAD/blob/master/EvalKit/THUMOS14_evalkit_20150930/annotation/detclasslist.txt) of them.

**Comment by jalaxy33** [comment]
OK, I see. Thanks for explaining.
