### ISSUE TITLE
About mAp

### ISSUE THREAD

**Issue by shadowclouds** [HYPJUDY/Decouple-SSAD#18]
Thanks for your excellent work!
I run sh run.sh and use the default config.But the result is 0.5 points lower than the results that you provided.
Could you tell me how to reach the results of the pretrained model that you provides?
or Could you provide more training details about your pretrained model?
Thanks for sharing!

**Comment by HYPJUDY** [comment]
Hi. I use the exactly code in this repository to get the model and results. As I mentioned in https://github.com/HYPJUDY/Decouple-SSAD#performance, the performance may fluctuate 0.5~2% at each training even with the same environment and code. Thus your result is normal. You can try to run multiple times to see whether you can get better results.

**Comment by shadowclouds** [comment]
Thanks for your quick reply!
