### ISSUE TITLE
Could you provide feature on ActivityNet?

### ISSUE THREAD

**Issue by shadowclouds** [HYPJUDY/Decouple-SSAD#20]
Hello, Thanks for your excellent work. I modified your work and wants to eval it at ActivityNet. However, i don't know how to extract feature or where coule i find features? Could you provide some help. Thanks so much and sorry to disturb.

**Comment by HYPJUDY** [comment]
Hi, you could follow the way similar to THUMOS14 to [Preprocess Data by Yourself](https://github.com/HYPJUDY/Decouple-SSAD/blob/master/data/README.md#preprocess-data-by-yourself). Or you could try to use ActivityNet features from other action detectionn works (e.g., [BSN](https://github.com/wzmsltw/BSN-boundary-sensitive-network)). 
Also, maybe discussions in other issues could shed some light on feature extraction / ActivityNet problem (e.g. https://github.com/HYPJUDY/Decouple-SSAD/issues/2).
Thanks.

**Comment by shadowclouds** [comment]
Thanks for your quick reply!
