### ISSUE TITLE
question about extract feature

### ISSUE THREAD

**Issue by mrlihellohorld** [HYPJUDY/Decouple-SSAD#25]
Hi, May I ask that frames should be extracted first and saved , Can they be directly extracted from video online? This can save disk space

**Comment by HYPJUDY** [comment]
Sure it is possible. But the feature extraction process costs a lot of time, and the online features cannot be re-used, extracting features online is not suggested.

**Comment by mrlihellohorld** [comment]
> Sure it is possible. But the feature extraction process costs a lot of time, and the online features cannot be re-used, extracting features online is not suggested.

I may not have expressed my problem clearly . In my opinion, feature extraction can be based on frame and video. If it is based on frame, a large space is required; if it is based on video, much space can be saved. Why not extract features based on video?
I found here, https://github.com/open-mmlab/mmaction/blob/master/DATASET.md also said,'For action recognition, both formats are supported. For temporal Action detection and spatial-temporal action detection, we still recommend the format of raw frames.', now i wannt to make temporal action detection,but i don't have enought space, could u give me some advice?
