### ISSUE TITLE
window size of activitynet

### ISSUE THREAD

**Issue by 666zcli** [HYPJUDY/Decouple-SSAD#3]
hi，thanks for you excellent work. I found that an issue mentioned that you had some experiments on activitynet. Due to the differences between duration of videos in activitynet. So could you tell me what window size you use in your experiment on activitynet? Thanks

**Comment by HYPJUDY** [comment]
Hi,
As mentioned in https://github.com/HYPJUDY/Decouple-SSAD/issues/2
"ActivityNet has larger scale in video length and action instance length (can be very short and very long).“
It's hard to set a proper window size which can cover most of the action instances for Anet, so I resize all videos to the same length (256 or 512) and use more (7 or 9) anchor layers. Maybe this manner of resizing videos will loss precision but [BSN](https://arxiv.org/abs/1806.02964) gets good performance with resized videos.

If you don't want to resize videos, then maybe you can try large window size like 1024?

**Comment by 666zcli** [comment]
Thanks for your advice!
